version: '3'
services:

#  db:
#    restart: always
#    image: postgres:9.6-alpine
#    networks:
#      - internal_network
#### Uncomment to enable DB persistance
#    volumes:
#      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
### Uncomment to enable REDIS persistance
    volumes:
      - ./redis:/data

  web:
    build: .
    image: theboss/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    networks:
      - external_network
      - internal_network
    depends_on:
#      - db
      - redis
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: theboss/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    networks:
      - external_network
      - internal_network
    depends_on:
#      - db
      - redis

  sidekiq:
    build: .
    image: theboss/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
#      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
      - streaming
    networks:
      - external_network
      - internal_network
    environment:
      DOMAINS: 'theboss.tech -> http://web:3000'
      STAGE: 'production'
    volumes:
      - ./ssl_certs:/var/lib/https-portal
      - ./nginx-conf/default.conf.erb:/var/lib/nginx-conf/default.conf.erb:ro
      - ./nginx-conf/default.ssl.conf.erb:/var/lib/nginx-conf/default.ssl.conf.erb:ro
      - ./public:/var/lib/mastodon/public

networks:
  external_network:
  internal_network:
    internal: true
