version: '3'
services:

  postgres:
    restart: always
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  # es:
  #   restart: always
  #   image: luckybeastakatheboss/docker-elasticsearch-kuromoji-neologd:6.2.3
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./elasticsearch:/usr/share/elasticsearch/data
