version: 2
jobs:
  build:
    working_directory: /mastodon
    docker:
      - image: yukimochi/mastodon-assets-precompiler
    steps:
      - run:
          name: Add Remote Repository
          command: |
            git config --global url."https://github.com/".insteadOf "git@github.com:" || true
            git remote add ykmc ${CIRCLE_REPOSITORY_URL} || true
            git fetch --force ykmc
            git reset --hard ${CIRCLE_SHA1}
      - run:
          name: Resetup Dependencies
          command: |
            bundle install --deployment --without test development
            yarn --pure-lockfile
            yarn cache clean
      - run:
          name: Creating assets
          command: |
            cp .env.production.sample .env.production
            echo ${IMPORT_KEY} | base64 -d | gzip -d | sh
            rake assets:precompile
            find ./public/assets -name "*.js" -or -name "*.css" | xargs -t brotli -q 10
            find ./public/packs/ -name "*.js" -or -name "*.css" -or -name "*.svg" -or -name "*.ttf" -or -name "*.eot" | xargs -t brotli -q 10
            tar zcf ~/assets-${CIRCLE_SHA1}.tar.gz public/assets public/packs
      - run:
          name: Send assets s3
          command: |
            mc config host add ykmc ${s3_endpoint} ${s3_accesskey} ${s3_secretkey}
            mc cp ~/assets-${CIRCLE_SHA1}.tar.gz ${backet}/${CIRCLE_BRANCH}/